@api_host = http://localhost:8000
@cookie =

POST {{api_host}}/api/tokens/create
Content-Type: application/json

{
    "phone":"+8201058625673"
}
###


POST {{api_host}}/api/getProfile
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNjY0MjQ0MTU3LCJleHAiOjE2NjQyNDc3NTcsIm5iZiI6MTY2NDI0NDE1NywianRpIjoiUUdSa2JJcUxGbzNiOGp1YyIsInN1YiI6IjUiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.gOoL24kA-jf8OE6bONXX2lKMIktl0Nc8Mu9_ITEtyvQ

{
    "phone":"+8201058625673"
}
###


###
GET {{api_host}}/api/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNjY0MjA0MjQ4LCJleHAiOjE2NjQyMDc4NDgsIm5iZiI6MTY2NDIwNDI0OCwianRpIjoieWJWS0drRFRMdUR1OWEwRyIsInN1YiI6IjQiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.AUCGwxoDjZdIsBDVSrGIUvh0AC3Bdz37wzgZDjc3x9w
Accept: application/json

{

}
###


POST {{api_host}}/api/login
Content-Type: application/json

{
    "email": "100862@qq.com",
    "password": "1234567"
}
###



############################# member



POST {{api_host}}/api/tokens/create2
Content-Type: application/json

{

}
###


POST {{api_host}}/api/login2
Content-Type: application/json

{
    "phone": "+8201058625673",
    "password": "12345678"
}
###


GET {{api_host}}/api/getProfile2
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luMiIsImlhdCI6MTY2NDI1MzI5NSwiZXhwIjoxNjY0MjU2ODk1LCJuYmYiOjE2NjQyNTMyOTUsImp0aSI6InZFMTNvbmRRTmVCRXdQemMiLCJzdWIiOiIxIiwicHJ2IjoiODY2NWFlOTc3NWNmMjZmNmI4ZTQ5NmY4NmZhNTM2ZDY4ZGQ3MTgxOCIsInJvbGUiOiJhcGkyIn0.lHVfPNNa3_NippvdVHsQ9VyDzfemJJTsHQ1oY6EHfIY

{
    "phone":"+8201058625673"
}
###


GET {{api_host}}/api/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luMiIsImlhdCI6MTY2NDI1MzI5NSwiZXhwIjoxNjY0MjU2ODk1LCJuYmYiOjE2NjQyNTMyOTUsImp0aSI6InZFMTNvbmRRTmVCRXdQemMiLCJzdWIiOiIxIiwicHJ2IjoiODY2NWFlOTc3NWNmMjZmNmI4ZTQ5NmY4NmZhNTM2ZDY4ZGQ3MTgxOCIsInJvbGUiOiJhcGkyIn0.lHVfPNNa3_NippvdVHsQ9VyDzfemJJTsHQ1oY6EHfIY
Accept: application/json

{

}
###
